version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.2

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.2
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: jdk-dependencies-{{ checksum "build.gradle" }}
      - run: ./gradlew build test jacocoTestReport --console plain --info
      - save_cache:
          paths:
            - ~/.gradle
          key: jdk-dependencies-{{ checksum "build.gradle" }}
      - store_artifacts:
          path: build/reports/jacoco/test/html
          destination: code-coverage
      - persist_to_workspace:
          root: .
          paths:
            - build/jib-image.tar

workflows:
  build-and-deploy:
    jobs:
      - build
      - aws-ecr/build-and-push-image:
          repo: "autopartner"
          context: "AP Dev"
          requires:
            - build
