version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.2
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: jdk-dependencies-{{ checksum "build.gradle" }}
      - run: ./gradlew build --console plain --info
      - save_cache:
          paths:
            - ~/.gradle
          key: jdk-dependencies-{{ checksum "build.gradle" }}

workflows:
  build-and-deploy:
    jobs:
      - build
